destination: _site/
url: "http://127.0.0.1:4013"
baseurl: "/cti110-pdf"
port: 4013
output: pdf
product: cti110
print_title: Blain's World @ ACC — cti110 class
print_subtitle: version 6.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: cti110_sidebar
